[package]
name = "serde_dotenv"
version = "0.1.0"
edition = "2024"
homepage = "https://github.com/rysndavjd/serde_dotenv"
repository = "https://github.com/rysndavjd/serde_dotenv"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0.228", default-features = false, features = ["alloc"]}

[features]
default = ["std"]
std = ["serde/std"]
