[package]
name = "serde_dotenv"
version = "0.1.0"
edition = "2024"
homepage = "https://github.com/rysndavjd/serde_dotenv"
repository = "https://github.com/rysndavjd/serde_dotenv"
license = "MIT OR Apache-2.0"

[dependencies]
embedded-io = "0.7.1"
indexmap = "2.14.0"
itoa = "1.0.18"
serde = { version = "1.0.228", default-features = false, features = ["alloc", "derive"]}
zmij = "1.0.21"

[features]
default = ["std"]
std = ["serde/std"]
